version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: timegate-api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    volumes:
      - ./api/uploads:/app/uploads
