-- Lot D / Notifications SaaS — congés + quotas abonnement
ALTER TYPE "TimeGateNotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REQUEST_PENDING';
ALTER TYPE "TimeGateNotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_APPROVED';
ALTER TYPE "TimeGateNotificationType" ADD VALUE IF NOT EXISTS 'LEAVE_REJECTED';
ALTER TYPE "TimeGateNotificationType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_QUOTA_WARNING';
ALTER TYPE "TimeGateNotificationType" ADD VALUE IF NOT EXISTS 'SUBSCRIPTION_QUOTA_REACHED';
