ALTER TABLE "tabCompany"
  ADD COLUMN IF NOT EXISTS "logo_url" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "phone" VARCHAR(50),
  ADD COLUMN IF NOT EXISTS "email" VARCHAR(140),
  ADD COLUMN IF NOT EXISTS "website" VARCHAR(500),
  ADD COLUMN IF NOT EXISTS "address" VARCHAR(500);
